# Site settings
title: Samed Yuksel
twitter_username: SamedYksel
name: Samed Yüksel

# Build settings
markdown: kramdown

#User specific content
#Links that will appear in the navbar
primarylinks:
 - title: Personal web site
   url: https://samedyuksel.github.io/cv
 - title: GitHub
   url: https://github.com/samedyuksel
 - title: StackOverflow
   url: https://stackoverflow.com/users/14229650/samed-yuksel
 - title: LinkedIn
   url: https://www.linkedin.com/in/samedyuksel

#Any buzzword skills you want to include
skills:
 - Java
 - Spring
 - C#
 - Angular
 - React
 - JPA
 - SQL
 - REST


#Work experience is required
roles:
 - title: Intern
   start: 7/19
   end: 8/19
   employer: Embedded System Software Developer
   description: programming microprocessor and circuit design.

#Education is required
education:
 - level: Bachelor of Engineering (B.Sc.)
   date: 2020
   subject: Computer Engineering
   school: Erciyes University

#This section is optional (as is the image link below)

#This section is optional - embeds slideshows from speakerdeck
# to get the speakerdeck ID copy the embed code and look for the data-it attribute


#List of interesting Github repo/projects to include - optional
github:
 - samedyuksel/smartFarm
 - samedyuksel/stajTakip
 - samedyuksel/AirHockeyGame_JavaScript

#Stackoverflow flair is optional


intro: | 
I started learning programming in 2014. The first language I learned is C. I stepped into object oriented programming with C# and reinforced it with Java. I focused on .Net and Spring technologies. Later I learned JavaScript, React and Angular. I developed this page with Angular.
|  

#An additional info freetext section is optional at the bottom of the page - can be text or HTML
